---

- name: install influxdb related packages
  yum: name={{ item }} state=present
  with_items:
    - influxdb

- name: template /etc/influxdb/influxdb.conf
  template: src=etc/influxdb/influxdb.conf.j2
            dest=/etc/influxdb/influxdb.conf
            mode=644 backup=yes
  notify: restart influxdb

- name: start and enable influxdb
  service: name={{ item }} state=started enabled=yes
  with_items:
    - influxdb
